env: "development"
server_address: "0.0.0.0:8080"
debug: true
gin_mode: "debug"
server_url: "http://localhost:8080"

db_driver: "postgres"
db_host: "localhost"
db_port: 5432
db_user: "root"
db_password: "secret"
db_name: "beshorter"
